excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            少有人走的路
tagline:          '又一个技术博客'
description:      '享受探索和创造带来的乐趣'
aboutme:          '生活在魔都的一枚码农。平时喜欢阅读、瞎折腾、还有写点东西。'
url:              http://yiheng.github.io
baseurl:          /

author:
  name:           'Ian Won'
  url:            http://yiheng.github.io/

paginate:         5
