excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            以恒的个人博客
tagline:          ''
description:      '多实践，多思考。思考的最好方式是写作。'
name:             '以恒'
url:              http://yiheng.github.io
baseurl:          http://yiheng.github.io/

author:
  name:           'Ian Wong'
  url:            http://yiheng.github.io/

paginate:         5
